services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobvita_local
    ports:
      - "8000:8000"
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"
      REVITA_URL: "https://revita-test.cs.helsinki.fi/api"
      ENVIRONMENT: "development"
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
      TZ: "Europe/Helsinki"
    volumes:
      - ./:/usr/src/app
      # IMPORTANT: use a named volume for node_modules so you don't use host node_modules
      - mobvita_node_modules:/usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]

volumes:
  mobvita_node_modules: {}